---
user:
  name: "{{ lookup('env', 'USER') }}"
  home: "{{ lookup('env', 'HOME') }}"
ubuntu_codename: "{{ lookup('pipe','. /etc/os-release && echo $UBUNTU_CODENAME')}}"

dotfiles: "{{ user.home }}/.dotfiles"

# Deb versions
albert_version: 0.16.1
bat_version: 0.12.1
rambox_version: 0.6.9
slack_version: 4.1.1
jetbrains_toolbox_version: 1.15.5796
wifi_driver_version: 1.176
docker_cred_helper_version: "v0.6.3"
