---

- name: Install Git
  apt:
    name: git

- name: Add lazygit ppa
  apt_repository:
    repo: ppa:lazygit-team/release

- name: Install lazygit
  apt:
    name: lazygit
    
- name: Install diff-so-fancy
  yarn:
    name: diff-so-fancy
    global: yes
    state: latest
